name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      # Check out your repository
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      # Set up JDK 17 (adjust if needed)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Build the project and run tests (this will also generate the Jacoco report)
      - name: Build project and run tests
        run: mvn clean verify

      # Copy the Jacoco XML report into the .qodana/code-coverage directory
      - name: Prepare code coverage report for Qodana
        run: |
          mkdir -p .qodana/code-coverage
          cp target/jacoco-report/jacoco.xml .qodana/code-coverage/coverage.xml

      # Run Qodana so it picks up the coverage report
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.3
        with:
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_1092412569}}
